export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Haupt Entitäten",
    "editor.solar_section": "Solar/PV",
    "editor.grid_section": "Netz Import/Export",
    "editor.battery_section": "Batterie",
    "editor.consumers_section": "Zusätzliche Verbraucher",
    "editor.options_section": "Darstellung & Optionen",
    "editor.group_layout": "Layout & Ansicht",
    "editor.group_appearance": "Effekte & Darstellung",
    "editor.group_pipes": "Röhren & Verbraucher",
    "editor.group_compact": "Kompakte Ansicht (evcc)",
    "editor.compact_view_enable": "Kompakte Ansicht aktivieren",
    "editor.compact_glow": "Neon Glow in kompakter Ansicht",
    "editor.compact_icons_in_bracket": "Icons in die Klammern setzen",
    "editor.compact_icons_in_bracket_hint": "Aus: Die Icons stehen innerhalb der Klammern, die Klammerlinie läuft durchgehend. An: Die Icons sitzen mittig auf der Klammerlinie und unterbrechen sie.",
    "editor.compact_bar_selfuse": "Einspeisung in den Balken aufnehmen",
    "editor.compact_bar_selfuse_hint": "Aus: Der mittlere Balken zeigt nur die Quellen (Solar, Batterie, Netz) in voller Höhe, die Einspeisung erscheint allein als Klammer darunter. An: Die Einspeisung wandert als eigenes farbiges Segment in den mittleren Balken — Solar und Batterie zeigen dann nur noch den Anteil, der wirklich im Haus verbraucht wird. Die Klammern oben zeigen unverändert die vollen Quellen.",
    "editor.battery_charge_color": "🔋 Ladung",
    "editor.battery_discharge_color": "⚡ Entladung",
    "editor.battery_split_color_hint": "In der kompakten Ansicht lassen sich Ladung und Entladung getrennt einfärben. Bubble = Balkensegment, Pipe = Klammerlinie, Text = Wert, Icon = Symbol, Secondary = Beschriftung in der Detailliste.",
    "editor.flow_rate_title": "Flussraten (W) an Röhren anzeigen",
    "editor.invert_battery": "Wert umkehren (+/-)",
    "editor.label_toggle": "Label im Kreis anzeigen",
    "editor.compact_view": "Kompakte Ansicht (evcc)",
    "editor.horizontal_view": "Horizontale Ansicht",
    "editor.diamond_view": "Diamant Ansicht",
    "editor.use_boxes": "Boxen mit runden Ecken statt Kreise",
    "editor.compact_details": "Details für Kompakte Ansicht",
    "editor.hide_inactive": "Inaktive Röhren ausblenden",
    "editor.entity": "Kombinierter Batterie Sensor (W)",
    "editor.label": "Beschriftung",
    "editor.icon": "Icon",
    "editor.back": "Zurück",
    "editor.battery_soc_label": "Ladestand (%)",
    "editor.house_total_title": "🏠 Gesamtverbrauch (optional)",
    "editor.house_sensor_label": "Sensor für Hausverbrauch (optional)",
    "editor.house_sensor_hint": "Wird benötigt, damit das Haus-Icon anklickbar ist (more-details). Ansonsten wird der Hausverbrauch berechnet.",
    "editor.consumer_1_title": "🚗 Links (Lila)",
    "editor.consumer_2_title": "♨️ Mitte (Orange)",
    "editor.consumer_3_title": "🏊 Rechts (Türkis)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/Haus)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Farbiger Hintergrund in Kreisen",
    "editor.colored_values": "Farbige Textwerte",
    "editor.hide_consumer_icons": "Icons unten ausblenden",
    "editor.invert_consumer": "Sensorwert invertieren (+/-)",
    "editor.invert_grid": "Wert umkehren (+/-)",
    "editor.secondary_sensor": "Zweiter Sensor (nur Anzeige)",
    "editor.tertiary_sensor": "Dritter Sensor (nur Anzeige)",
    "editor.tertiary_sensor_hint": "Zweiter und dritter Sensor werden in einer Zeile mit \" / \" getrennt angezeigt und nutzen beide die Secondary-Farbe.",
    "editor.grid_to_battery_sensor": "Netz-zu-Batterie Sensor (W, Optional)",
    "editor.grid_to_battery_hint": "Optional: separater Sensor für den Netz-zu-Batterie Fluss. Wenn leer, wird der Wert automatisch berechnet.",
    "editor.grid_combined_sensor": "Kombinierter Netz-Sensor (W, Optional)",
    "editor.grid_combined_hint": "Ein Sensor für Import UND Export: positiv = Import, negativ = Export. Überschreibt den kombinierten Import/Export Sensor.",
    "editor.color_picker": "Bubble",
    "editor.pipe_color": "Pipe",
    "editor.export_color": "↑ Einspeisung / Export",
    "editor.export_color_hint": "Bubble färbt den Netz-Kreis beim Einspeisen, Pipe die Export-Röhre, Text den Wert, Icon das Symbol und Secondary die Beschriftung in der Detailliste der kompakten Ansicht. Alle folgen der Bubble-Farbe, solange sie nicht eigens gesetzt sind. Hinweis: Bubble wirkt in der kompakten Ansicht nur, wenn „Einspeisung in den Balken aufnehmen\" aktiv ist.",
    "editor.consumer_unit_kw": "Sensor meldet in kW",
    "editor.show_consumer_always": "Verbraucher bei null Watt anzeigen",
    "editor.battery_charge_sensor": "Batterie-Ladung Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Batterie-Entladung Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.consumer_hide_pipe": "Pipe bei geringer Leistung ausblenden",
    "editor.consumer_pipe_threshold": "Pipe-Schwellenwert (Watt)",
    "editor.consumer_not_set": "nicht gesetzt",
    "editor.consumer_standby": "Standby-Werte ausblenden",
    "editor.consumer_standby_threshold": "Standby-Schwellenwert (Watt)",
    "editor.consumer_standby_hint": "Werte unterhalb des Schwellenwerts werden als 0 W gewertet, der Verbraucher wird dadurch ausgeblendet.",
    "editor.text_color": "Text",
    "editor.icon_color": "Icon",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Batterie-Ladung über Hausverbrauch umleiten",
    "editor.battery_show_power": "Zeige Leistung statt SoC",
    "editor.solar_unit_kw": "Solar in kW anzeigen",
    "editor.grid_unit_kw": "Grid in kW anzeigen",
    "editor.battery_unit_kw": "Batterie in kW anzeigen",
    "editor.consumer_4_title": "⚡ Reihe 2 Links (Gelb)",
    "editor.consumer_5_title": "💡 Reihe 2 Rechts (Indigo)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Netz",
    "card.label_battery": "Batterie",
    "card.label_house": "Verbrauch",
    "card.label_car": "E-Auto",
    "card.label_heater": "Heizung",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Verbr. 4",
    "card.label_consumer_5": "Verbr. 5",
    "card.label_export": "Einspeisung",
    "card.label_in": "Erzeugung",
    "card.label_out": "Verbrauch",
  }
};
